### ISSUE TITLE
Language switch url gives Redirector error in content

### ISSUE THREAD

**Issue by drsdre** [akaunting/language#15]
Since using Laravel 5.8 I'm hitting on an error when I'm switching language using the language()->back($code) function. This error blocks in local (debug) mode, in production the route is followed. 
 
`ErrorException: Object of class Illuminate\Routing\Redirector could not be converted to string in file /project/vendor/symfony/http-foundation/Response.php on line 404
`

My language.php configuration:
    'route'         => true,
    'home'          => true,
    'url'          => false,
    'carbon'        => true,
    'date'          => false,
    'auto'          => true,
    'prefix'        => 'languages',
    'middleware'    => 'Akaunting\Language\Middleware\SetLocale',
    'mode'          => ['code' => 'short', 'name' => 'native'],

**Comment by jacquie-engbrecht** [comment]
I am having the same issue when I click on one of the language links after my session has expired.

**Comment by drsdre** [comment]
Found out that this issue occurs if the session expires between the page visit and the language switch. This is where it tries to use $session-previousUrl() which returns null and that cannot be redirected. Added a patch that returns the user to home see https://github.com/akaunting/language/pull/16

**Comment by zeroonnet** [comment]
Having same problem

**Comment by zeroonnet** [comment]
Having same problem. @drsdre solution works.

Since it's not merged yet, what I did was created a new controller extending `Akaunting\Language\Controllers\Language`

Copied methods `back` (the one we need to edit) and `setLocale` (because for some reason it's private)

Did @drsdre changes to the method `back`

Changed `controller` at `app/language.php` to the newly created controller

Working for now

**Comment by denisdulici** [comment]
Sorry guys for the late reaction, this has been fixed now.
